#!/bin/bash

cd $(dirname $0)

## Sometimes you need to...
random_sleep()
{
    SLEEP_TIME=$RANDOM
    let "SLEEP_TIME %= 15"
    sleep ${SLEEP_TIME}
}

./giddyup service wait scale

IP=$(giddyup ip myip)
META_URL="http://rancher-metadata.rancher.internal/2015-12-19"
CLUSTER_NAME=$(curl -sS ${META_URL}/self/stack/name)

echo
echo "Starting pxc..."
echo

if [ "$#" -eq "0" ]; then

    set -- mysqld --wsrep_cluster_name=$CLUSTER_NAME --wsrep_cluster_address=gcomm://$(./giddyup ip stringify) --wsrep_node_address="$IP" --wsrep_sst_auth="sstuser:$PXC_SST_PASSWORD"

    if [ giddyup leader check ] && [ ! -f "/opt/rancher/initialized" ]; then
        set -- mysqld --wsrep_cluster_name=$CLUSTER_NAME --wsrep_cluster_address=gcomm:// --wsrep_node_address="$IP" --wsrep_sst_auth="sstuser:$PXC_SST_PASSWORD"
        touch /opt/rancher/initialized
    else
        random_sleep
        export CLUSTER_JOIN=true
    fi
fi

exec /docker-entrypoint.sh "$@"