#!/bin/bash

cd $(dirname $0)

## Sometimes you need to...
random_sleep()
{
    SLEEP_TIME=$RANDOM
    let "SLEEP_TIME %= 15"
    sleep ${SLEEP_TIME}
}

./giddyup service wait scale

PXC_CONF='/etc/mysql/conf.d/001-pxc.cnf'

echo "Waiting for Config..."
while [ ! -f "${PXC_CONF}" ]; do
   sleep 5
done
echo "Starting pxc..."

if [ "$#" -eq "0" ]; then

    set -- mysqld --wsrep_cluster_address=gcomm://$(./giddyup ip stringify)

    if [ giddyup leader check ] && [ ! -f "/opt/rancher/initialized" ]; then
        set -- mysqld --wsrep_cluster_address=gcomm://
        touch /opt/rancher/initialized
    else
        random_sleep
    fi
fi

exec /docker-entrypoint.sh "$@"